// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.3
// source: proto/sketch.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Sketcher_MergeKll_FullMethodName        = "/proto.Sketcher/MergeKll"
	Sketcher_QueryKll_FullMethodName        = "/proto.Sketcher/QueryKll"
	Sketcher_ReverseQueryKll_FullMethodName = "/proto.Sketcher/ReverseQueryKll"
	Sketcher_PlotKll_FullMethodName         = "/proto.Sketcher/PlotKll"
	Sketcher_MergeCount_FullMethodName      = "/proto.Sketcher/MergeCount"
	Sketcher_QueryCount_FullMethodName      = "/proto.Sketcher/QueryCount"
	Sketcher_TestLatency_FullMethodName     = "/proto.Sketcher/TestLatency"
	Sketcher_BadKll_FullMethodName          = "/proto.Sketcher/BadKll"
	Sketcher_BadCount_FullMethodName        = "/proto.Sketcher/BadCount"
	Sketcher_MergeASketch_FullMethodName    = "/proto.Sketcher/MergeASketch"
	Sketcher_QueryASketch_FullMethodName    = "/proto.Sketcher/QueryASketch"
	Sketcher_RestartServer_FullMethodName   = "/proto.Sketcher/RestartServer"
)

// SketcherClient is the client API for Sketcher service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SketcherClient interface {
	// Merges a sketch into the main sketch
	MergeKll(ctx context.Context, in *KLLSketch, opts ...grpc.CallOption) (*MergeReply, error)
	QueryKll(ctx context.Context, in *NumericValue, opts ...grpc.CallOption) (*QueryReturn, error)
	ReverseQueryKll(ctx context.Context, in *ReverseQuery, opts ...grpc.CallOption) (*NumericValue, error)
	PlotKll(ctx context.Context, in *PlotRequest, opts ...grpc.CallOption) (*PlotKllReply, error)
	MergeCount(ctx context.Context, in *CountSketch, opts ...grpc.CallOption) (*MergeReply, error)
	QueryCount(ctx context.Context, in *NumericValue, opts ...grpc.CallOption) (*CountQueryReply, error)
	TestLatency(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*EmptyMessage, error)
	BadKll(ctx context.Context, in *BadArray, opts ...grpc.CallOption) (*MergeReply, error)
	BadCount(ctx context.Context, in *BadArray, opts ...grpc.CallOption) (*MergeReply, error)
	MergeASketch(ctx context.Context, in *ASketch, opts ...grpc.CallOption) (*MergeReply, error)
	QueryASketch(ctx context.Context, in *NumericValue, opts ...grpc.CallOption) (*CountQueryReply, error)
	RestartServer(ctx context.Context, in *RestartMessage, opts ...grpc.CallOption) (*EmptyMessage, error)
}

type sketcherClient struct {
	cc grpc.ClientConnInterface
}

func NewSketcherClient(cc grpc.ClientConnInterface) SketcherClient {
	return &sketcherClient{cc}
}

func (c *sketcherClient) MergeKll(ctx context.Context, in *KLLSketch, opts ...grpc.CallOption) (*MergeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MergeReply)
	err := c.cc.Invoke(ctx, Sketcher_MergeKll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sketcherClient) QueryKll(ctx context.Context, in *NumericValue, opts ...grpc.CallOption) (*QueryReturn, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryReturn)
	err := c.cc.Invoke(ctx, Sketcher_QueryKll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sketcherClient) ReverseQueryKll(ctx context.Context, in *ReverseQuery, opts ...grpc.CallOption) (*NumericValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NumericValue)
	err := c.cc.Invoke(ctx, Sketcher_ReverseQueryKll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sketcherClient) PlotKll(ctx context.Context, in *PlotRequest, opts ...grpc.CallOption) (*PlotKllReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlotKllReply)
	err := c.cc.Invoke(ctx, Sketcher_PlotKll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sketcherClient) MergeCount(ctx context.Context, in *CountSketch, opts ...grpc.CallOption) (*MergeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MergeReply)
	err := c.cc.Invoke(ctx, Sketcher_MergeCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sketcherClient) QueryCount(ctx context.Context, in *NumericValue, opts ...grpc.CallOption) (*CountQueryReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CountQueryReply)
	err := c.cc.Invoke(ctx, Sketcher_QueryCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sketcherClient) TestLatency(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*EmptyMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyMessage)
	err := c.cc.Invoke(ctx, Sketcher_TestLatency_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sketcherClient) BadKll(ctx context.Context, in *BadArray, opts ...grpc.CallOption) (*MergeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MergeReply)
	err := c.cc.Invoke(ctx, Sketcher_BadKll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sketcherClient) BadCount(ctx context.Context, in *BadArray, opts ...grpc.CallOption) (*MergeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MergeReply)
	err := c.cc.Invoke(ctx, Sketcher_BadCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sketcherClient) MergeASketch(ctx context.Context, in *ASketch, opts ...grpc.CallOption) (*MergeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MergeReply)
	err := c.cc.Invoke(ctx, Sketcher_MergeASketch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sketcherClient) QueryASketch(ctx context.Context, in *NumericValue, opts ...grpc.CallOption) (*CountQueryReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CountQueryReply)
	err := c.cc.Invoke(ctx, Sketcher_QueryASketch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sketcherClient) RestartServer(ctx context.Context, in *RestartMessage, opts ...grpc.CallOption) (*EmptyMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyMessage)
	err := c.cc.Invoke(ctx, Sketcher_RestartServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SketcherServer is the server API for Sketcher service.
// All implementations must embed UnimplementedSketcherServer
// for forward compatibility.
type SketcherServer interface {
	// Merges a sketch into the main sketch
	MergeKll(context.Context, *KLLSketch) (*MergeReply, error)
	QueryKll(context.Context, *NumericValue) (*QueryReturn, error)
	ReverseQueryKll(context.Context, *ReverseQuery) (*NumericValue, error)
	PlotKll(context.Context, *PlotRequest) (*PlotKllReply, error)
	MergeCount(context.Context, *CountSketch) (*MergeReply, error)
	QueryCount(context.Context, *NumericValue) (*CountQueryReply, error)
	TestLatency(context.Context, *EmptyMessage) (*EmptyMessage, error)
	BadKll(context.Context, *BadArray) (*MergeReply, error)
	BadCount(context.Context, *BadArray) (*MergeReply, error)
	MergeASketch(context.Context, *ASketch) (*MergeReply, error)
	QueryASketch(context.Context, *NumericValue) (*CountQueryReply, error)
	RestartServer(context.Context, *RestartMessage) (*EmptyMessage, error)
	mustEmbedUnimplementedSketcherServer()
}

// UnimplementedSketcherServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSketcherServer struct{}

func (UnimplementedSketcherServer) MergeKll(context.Context, *KLLSketch) (*MergeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MergeKll not implemented")
}
func (UnimplementedSketcherServer) QueryKll(context.Context, *NumericValue) (*QueryReturn, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryKll not implemented")
}
func (UnimplementedSketcherServer) ReverseQueryKll(context.Context, *ReverseQuery) (*NumericValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReverseQueryKll not implemented")
}
func (UnimplementedSketcherServer) PlotKll(context.Context, *PlotRequest) (*PlotKllReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlotKll not implemented")
}
func (UnimplementedSketcherServer) MergeCount(context.Context, *CountSketch) (*MergeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MergeCount not implemented")
}
func (UnimplementedSketcherServer) QueryCount(context.Context, *NumericValue) (*CountQueryReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryCount not implemented")
}
func (UnimplementedSketcherServer) TestLatency(context.Context, *EmptyMessage) (*EmptyMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestLatency not implemented")
}
func (UnimplementedSketcherServer) BadKll(context.Context, *BadArray) (*MergeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BadKll not implemented")
}
func (UnimplementedSketcherServer) BadCount(context.Context, *BadArray) (*MergeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BadCount not implemented")
}
func (UnimplementedSketcherServer) MergeASketch(context.Context, *ASketch) (*MergeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MergeASketch not implemented")
}
func (UnimplementedSketcherServer) QueryASketch(context.Context, *NumericValue) (*CountQueryReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryASketch not implemented")
}
func (UnimplementedSketcherServer) RestartServer(context.Context, *RestartMessage) (*EmptyMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestartServer not implemented")
}
func (UnimplementedSketcherServer) mustEmbedUnimplementedSketcherServer() {}
func (UnimplementedSketcherServer) testEmbeddedByValue()                  {}

// UnsafeSketcherServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SketcherServer will
// result in compilation errors.
type UnsafeSketcherServer interface {
	mustEmbedUnimplementedSketcherServer()
}

func RegisterSketcherServer(s grpc.ServiceRegistrar, srv SketcherServer) {
	// If the following call pancis, it indicates UnimplementedSketcherServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Sketcher_ServiceDesc, srv)
}

func _Sketcher_MergeKll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KLLSketch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SketcherServer).MergeKll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sketcher_MergeKll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SketcherServer).MergeKll(ctx, req.(*KLLSketch))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sketcher_QueryKll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NumericValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SketcherServer).QueryKll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sketcher_QueryKll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SketcherServer).QueryKll(ctx, req.(*NumericValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sketcher_ReverseQueryKll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReverseQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SketcherServer).ReverseQueryKll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sketcher_ReverseQueryKll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SketcherServer).ReverseQueryKll(ctx, req.(*ReverseQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sketcher_PlotKll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SketcherServer).PlotKll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sketcher_PlotKll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SketcherServer).PlotKll(ctx, req.(*PlotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sketcher_MergeCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountSketch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SketcherServer).MergeCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sketcher_MergeCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SketcherServer).MergeCount(ctx, req.(*CountSketch))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sketcher_QueryCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NumericValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SketcherServer).QueryCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sketcher_QueryCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SketcherServer).QueryCount(ctx, req.(*NumericValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sketcher_TestLatency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SketcherServer).TestLatency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sketcher_TestLatency_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SketcherServer).TestLatency(ctx, req.(*EmptyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sketcher_BadKll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BadArray)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SketcherServer).BadKll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sketcher_BadKll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SketcherServer).BadKll(ctx, req.(*BadArray))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sketcher_BadCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BadArray)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SketcherServer).BadCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sketcher_BadCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SketcherServer).BadCount(ctx, req.(*BadArray))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sketcher_MergeASketch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ASketch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SketcherServer).MergeASketch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sketcher_MergeASketch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SketcherServer).MergeASketch(ctx, req.(*ASketch))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sketcher_QueryASketch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NumericValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SketcherServer).QueryASketch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sketcher_QueryASketch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SketcherServer).QueryASketch(ctx, req.(*NumericValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sketcher_RestartServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestartMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SketcherServer).RestartServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sketcher_RestartServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SketcherServer).RestartServer(ctx, req.(*RestartMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// Sketcher_ServiceDesc is the grpc.ServiceDesc for Sketcher service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sketcher_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Sketcher",
	HandlerType: (*SketcherServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MergeKll",
			Handler:    _Sketcher_MergeKll_Handler,
		},
		{
			MethodName: "QueryKll",
			Handler:    _Sketcher_QueryKll_Handler,
		},
		{
			MethodName: "ReverseQueryKll",
			Handler:    _Sketcher_ReverseQueryKll_Handler,
		},
		{
			MethodName: "PlotKll",
			Handler:    _Sketcher_PlotKll_Handler,
		},
		{
			MethodName: "MergeCount",
			Handler:    _Sketcher_MergeCount_Handler,
		},
		{
			MethodName: "QueryCount",
			Handler:    _Sketcher_QueryCount_Handler,
		},
		{
			MethodName: "TestLatency",
			Handler:    _Sketcher_TestLatency_Handler,
		},
		{
			MethodName: "BadKll",
			Handler:    _Sketcher_BadKll_Handler,
		},
		{
			MethodName: "BadCount",
			Handler:    _Sketcher_BadCount_Handler,
		},
		{
			MethodName: "MergeASketch",
			Handler:    _Sketcher_MergeASketch_Handler,
		},
		{
			MethodName: "QueryASketch",
			Handler:    _Sketcher_QueryASketch_Handler,
		},
		{
			MethodName: "RestartServer",
			Handler:    _Sketcher_RestartServer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/sketch.proto",
}
